name = "Llama2Inference"
uuid = "0c4a77e8-068d-4055-9a7e-2c98ca11fac7"
authors = ["Veronika Dimitrova <veronika.dimitrova@campus.tu-berlin.de>", "Johann-Ludwig Herzog <herzog.2@campus.tu-berlin.de>", "Phi Long Mikesch <mikesch@campus.tu-berlin.de>", "Yang Felix Wang <yang.f.wang@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"
