name = "Llama2Inference"
uuid = "0c4a77e8-068d-4055-9a7e-2c98ca11fac7"
authors = ["Veronika Dimitrova <veronika.dimitrova@campus.tu-berlin.de>", "Johann-Ludwig Herzog <herzog.2@campus.tu-berlin.de>", "Phi Long Mikesch <mikesch@campus.tu-berlin.de>", "Yang Felix Wang <yang.f.wang@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
DataStructures = "0.18"
StringEncodings = "0.3"
julia = "1.10"
